#ifndef TOF_IMAGINGALGORITHM_GLOBAL_H
#define TOF_IMAGINGALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOF_IMAGINGALGORITHM_LIBRARY)
#  define TOF_IMAGINGALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOF_IMAGINGALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOF_IMAGINGALGORITHM_GLOBAL_H
