language: python
os: linux
dist: focal
python:
  - 3.7
  - 3.8

addons:
  apt:
    update: true

branches:
  only:
    - master

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#    packages:
    


install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - conda info -a
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - python setup.py install

script:
  - pytest -v --cov-report term --cov=tests/

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: always
  # Useful for debugging any issues with conda
  - conda info -a

  # - conda env create -n book -f environment.yml
  # - conda init zsh
  # - source /home/travis/miniconda/etc/profile.d/conda.sh



script:
  - ls 

