name: tofimaging
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - astropy
  - lmfit
  - matplotlib
  - numpy
  - scikit-image
  - scipy
  - tqdm==4.36.1
  - qtpy
  - pyqtgraph
  - tqdm
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - ipywe
    - NeuNorm
    - neutronbraggedge
    - inflect
